# https://render.com/deploy?repo=https://github.com/iKennas/kennas-insta
services:
  - type: web
    name: kennas-insta-api
    runtime: docker
    plan: free
    healthCheckPath: /api/health
    envVars:
      - key: PORT
        value: "8080"
